# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eybvQtrFzumhx3DDncCWL2MVamaEzGdV
"""

import streamlit as st
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

st.title("Life Insurance Policy Predictor")
st.write("This app uses an AdaBoost model to predict policy type.")

dataset = pd.read_csv("life_insurance_retention_dataset_full.csv")

# Drop columns that should not be used as prediction inputs
X = dataset.drop(columns=["policy_type", "customer_id", "name", "policy_start_date"])
y = dataset["policy_type"]

labelencoder = LabelEncoder()
y_encoded = labelencoder.fit_transform(y)

categorical_cols = X.select_dtypes(include=["object", "string"]).columns.tolist()
numerical_cols = X.select_dtypes(include=["number"]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", StandardScaler(), numerical_cols)
    ]
)

model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=4, criterion="entropy", random_state=0),
    n_estimators=100,
    learning_rate=0.1,
    random_state=0
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

pipeline.fit(X, y_encoded)

st.subheader("Enter Customer Information")

input_data = {}

for col in X.columns:
    if col in categorical_cols:
        options = sorted(X[col].dropna().astype(str).unique())
        input_data[col] = st.selectbox(col.replace("_", " ").title(), options)
    else:
        input_data[col] = st.number_input(
            col.replace("_", " ").title(),
            value=float(pd.to_numeric(X[col], errors="coerce").mean())
        )

input_df = pd.DataFrame([input_data])

if st.button("Predict Policy Type"):
    prediction = pipeline.predict(input_df)
    result = labelencoder.inverse_transform(prediction)[0]
    st.success(f"Predicted Policy Type: {result}")
