# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eybvQtrFzumhx3DDncCWL2MVamaEzGdV
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
pipeline = joblib.load("adaboost_pipeline.pkl")
labelencoder = joblib.load("label_encoder.pkl")

st.title("Life Insurance Policy Predictor")

# Load dataset for input structure
dataset = pd.read_csv("life_insurance_retention_dataset_full.csv")
X = dataset.drop(columns=["policy_type"])

st.subheader("Enter Customer Info")

input_data = {}

for col in X.columns:
    if X[col].dtype == "object":
        input_data[col] = st.selectbox(col, X[col].unique())
    else:
        input_data[col] = st.number_input(col, value=float(X[col].mean()))

input_df = pd.DataFrame([input_data])

if st.button("Predict"):
    prediction = pipeline.predict(input_df)
    result = labelencoder.inverse_transform(prediction)[0]
    st.success(f"Prediction: {result}")