# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQkSo7fdXmVK2lGiTOD_vj8s3abH5cnj
"""

import pandas as pd
import joblib

from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

# Load dataset
dataset = pd.read_csv("life_insurance_retention_dataset_full.csv")

# Split features and target
X = dataset.drop(columns=["policy_type"])
y = dataset["policy_type"]

# Encode target
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

# Column types
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Preprocessing
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
    ('num', StandardScaler(), numerical_cols)
])

# AdaBoost model
model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=4, criterion="entropy", random_state=0),
    n_estimators=100,
    learning_rate=0.1,
    random_state=0
)

# Pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

# Train model
pipeline.fit(X, y)

# Save files
joblib.dump(pipeline, "adaboost_pipeline.pkl")
joblib.dump(labelencoder, "label_encoder.pkl")

print("Files created successfully!")